name = "Steam n Rails Server Pack"
author = "IThundxr, SpottyTheTurtle"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62c26d60cbea937754c03c3b3831d1d1330346e2efe7c7e4f632c6367c5d8693"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"
