name = "Steam n Rails Server"
author = "SpottyTheTurtle"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a48236c1881dacb87181fc07c4232bff0a873997ec3236aca4ef12e347f137b7"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"
